"""add face encoding

Revision ID: 6afd8e954046
Revises: 8548cd98b10f
Create Date: 2026-07-29 14:46:43.114709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6afd8e954046'
down_revision: Union[str, Sequence[str], None] = '8548cd98b10f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('face_encoding', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'face_encoding')
    # ### end Alembic commands ###
